site_name: Research in Social Media, Block 4, 2021 @ TISEM
pages:
-  Course Home Page: index.md
- Announcements: announcements.md
- Schedule: schedule.md
- Course Material: material.md
- About the Instructors: about.md
# - Acknowledgements: acknowledgements.md
- License: license.md
- Citing Us: citation.md
theme: material
markdown_extensions:
  - admonition
  - pymdownx.superfences
