site_name: Programming Practices for Research in Economics
pages:
-  Course Home Page: : index.md
- Schedule: schedule.md
- Course Material: material.md
- About the Instructors: about.md
- Acknowledgements: acknowledgements.md
theme: material
